esphome:
  name: water-tank-monitor
  friendly_name: water_tank_monitor
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: esp-idf

logger:

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

binary_sensor:
  - platform: gpio
    id: tank_one_sensor
    name: "Tank Level Sensor 1"
    pin:
      number: GPIO9
      inverted: false
      mode:
        input: true
        pullup: true
    device_class: moisture

  - platform: gpio
    id: tank_two_sensor
    name: "Tank Level Sensor 2"
    pin:
      number: GPIO10
      inverted: false
      mode:
        input: true
        pullup: true
    device_class: moisture

  - platform: gpio
    id: tank_three_sensor
    name: "Tank Level Sensor 3"
    pin:
      number: GPIO8
      inverted: false
      mode:
        input: true
        pullup: true
    device_class: moisture
